
export const countryMapping: { [key: string]: string } = {
    AU: 'Australia',
    BR: 'Brazil',
    CA: 'Canada',
    CH: 'Switzerland',
    DE: 'Germany',
    DK: 'Denmark',
    ES: 'Spain',
    FI: 'Finland',
    FR: 'France',
    GB: 'United Kingdom',
    IE: 'Ireland',
    IN: 'India',
    IR: 'Iran',
    MX: 'Mexico',
    NL: 'Netherlands',
    NO: 'Norway',
    NZ: 'New Zealand',
    RS: 'Serbia',
    TR: 'Turkey',
    UA: 'Ukraine',
    US: 'United States',
  };
  

export const nationalityOptions = [
  { value: 'AU', label: 'Australia' },
  { value: 'BR', label: 'Brazil' },
  { value: 'CA', label: 'Canada' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'DE', label: 'Germany' },
  { value: 'DK', label: 'Denmark' },
  { value: 'ES', label: 'Spain' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IN', label: 'India' },
  { value: 'IR', label: 'Iran' },
  { value: 'MX', label: 'Mexico' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'NO', label: 'Norway' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'RS', label: 'Serbia' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'US', label: 'United States' },
];
